services:
  db:
    image: mongo
    container_name: mongodb
    restart: always
    env_file:
      - ./db/.env
    networks:
      - bk
    ports:
      - "27018:27017"
    volumes:
      - ./db/import:/tmp/import
      - ./db/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "-u",
          "admin",
          "-p",
          "secret",
          "--authenticationDatabase",
          "admin",
          "--quiet",
          "--eval",
          "db.runCommand({ ping: 1 }).ok",
        ]
      interval: 10s
      retries: 5
      start_period: 10s

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    env_file:
      - ./mongo-express/.env
    networks:
      - bk
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy

networks:
  bk:
    driver: bridge
